name: ACMEReal
channels:
  - defaults
  - pytorch
  - fair-robotics
  - aihabitat
  - conda-forge
dependencies:
  - python=3.8
  - zarr
  - tqdm
  - h5py
  - Flask
  - docker-py
  - blosc
  - librealsense
  - Pillow
  - hydra-core
  - paramiko
  - pip
  - pip:
      - opencv-contrib-python
      - pyrealsense2
      - pyzmq
      - scipy

