name: ACMEReal
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - zarr
  - tqdm
  - h5py
  - blosc
  - librealsense
  - Pillow
  - hydra-core
  - scipy
  - pip
  - pip:
      - opencv-contrib-python
      - pyrealsense2
      - panda-python
      - torch

