policy:
  control_frequency: 0.7
  obs_history: 2
  action_horizon: 16
  action_start_offset: 2
  rgb_keys: ["rgb_0", "rgb_1"]
  lowdim_keys: ["eef_pos", "eef_quat", "gripper_force"]
  delta_actions: false
  port: 54295
  frame_shape:
    - 3
    - 256
    - 256