# @package _group_
instruction: "Pick up the object and place it at the target location"

home_pos: [0.30582778, 0., 0.48467681]
home_rot: [1., 0., 0., 0.]

# Full 6-DOF control with gripper actuation.
pos_mask: [true, true, true]

freeze_rotation: false
freeze_gripper: false
