max_episode_timesteps: 590
episodes_path: "/mnt/ssd/james/episodes"

nuc:
  ip: "192.168.1.106"
  franka_ip: "192.168.1.107"
  server:
    ip: ${nuc.ip}
    port: 22
    robot_port: 50051
    gripper_port: 50052
    user: ${env:NUC_USER}
    pwd: ${env:NUC_PWD}
    conda: "/home/james/anaconda3"

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15

writer:
  max_episode_len: ${max_episode_timesteps}
  n_cameras: 6
  instruction: "Push the green T shape into the black outline of the T shape on the table"
  calibration_path: "/home/rvl_root/.config/JetBrains/PyCharm2025.2/scratches/calib.yaml"
  captures:
    frame_width: ${realsense.width}
    frame_height: ${realsense.height}
    max_episode_len: ${writer.max_episode_len}
    fps: ${realsense.fps}

gello:
  base_index: 8
  baud_rate: 115200
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2FX-if00-port0"
  joint_signs:
    - 1
    - 1
    - 1
    - -1
    - 1
    - -1
    - 1
  start_joints:
    - 0
    - 0
    - 0
    - -1.57
    - 0
    - 1.57
    - 0
  gripper:
    open: 2 # from logging the dynamixel joint vals
    closed: 1.5
    sign: -1

hydra:
  output_subdir: null
  run:
    dir: .