defaults:
  - task: pusht

max_episode_timesteps: 250
episodes_path: "/mnt/ssd/james/episodes"

nuc:
  ip: "192.168.1.106"
  franka_ip: "192.168.1.107"
  home_pos: ${task.home_pos}
  home_rot: ${task.home_rot}
  server:
    gripper_hysteresis: 0.1  # Dead zone: grasp if > 0.5+h, open if < 0.5-h

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15
  laser_power: 0  # IR projector power (0=off, 1-360mW). 0 recommended for FoundationStereo.

writer:
  max_episode_len: ${max_episode_timesteps}
  instruction: ${task.instruction}
  captures:
    frame_width: ${realsense.width}
    frame_height: ${realsense.height}
    max_episode_len: ${writer.max_episode_len}
    fps: ${realsense.fps}

gello:
  base_index: 0
  baud_rate: 115200
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2CD-if00-port0"
  joint_signs:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  start_joints:
    - 0
    - 0
    - 0
    - -1.57
    - 0
    - 1.57
    - 0
  gripper:
    open: 0.35 # from logging the dynamixel joint vals
    closed: -0.62
    sign: -1

hydra:
  output_subdir: null
  job_logging: null
  run:
    dir: .
