defaults:
  - policy: default

max_episode_timesteps: 1000
start_index: 0



writer:
  max_episode_len: ${max_episode_timesteps}

nuc:
  ip: "192.168.1.106"
  franka_ip: "192.168.1.107"
  server:
    ip: ${nuc.ip}
    port: 22
    robot_port: 50051
    gripper_port: 50052
    user: ${env:NUC_USER}
    pwd: ${env:NUC_PWD}
    conda: "/home/james/anaconda3"

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15
  obs_cams:
    - "148122060186" # side view
#    - "848312071702" # overhead
    - "217222061106" # wrist cam

hydra:
  output_subdir: null
  run:
    dir: .