max_episode_timesteps: 600
start_index: 0

policy:
  control_frequency: 1
  obs_history: 2
  rgb_keys: ["rgb_0", "rgb_1"]
  lowdim_keys: ["eef_pos", "eef_quat", "gripper_force"]
  delta_actions: false
  port: 54070
  frame_shape:
    - 3
    - 256
    - 256

writer:
  max_episode_len: ${max_episode_timesteps}

nuc:
  ip: "192.168.1.106"
  franka_ip: "192.168.1.107"
  server:
    ip: ${nuc.ip}
    port: 22
    robot_port: 50051
    gripper_port: 50052
    user: ${env:NUC_USER}
    pwd: ${env:NUC_PWD}
    conda: "/home/james/anaconda3"

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15
  obs_cams:
    - "848312071702" # overhead
    - "217222061106" # wrist cam

hydra:
  output_subdir: null
  run:
    dir: .