defaults:
  - policy: default
  - task: pusht

max_episode_timesteps: 4000
start_index: 0



writer:
  max_episode_len: ${max_episode_timesteps}

nuc:
  ip: "192.168.1.106"
  franka_ip: "192.168.1.107"
  home_pos: ${task.home_pos}
  home_rot: ${task.home_rot}
  server:
    gripper_hysteresis: 0.1

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15
  obs_cams:
    - "148122060186" # high right
    # - "932122060415" # high left
#    - "848312071702" # overhead
    - "217222061106" # wrist cam
#    - "051222062898"

hydra:
  output_subdir: null
  run:
    dir: .