dtst_path: /home/rvl_root/Desktop/ACMERealWorld/policies/pusht/3d_pos_cam_0_4/dataset

sample_horizon: 8

policy:
  control_frequency: 1
  obs_history: 2
  action_horizon: 8
  action_start_offset: 2
  rgb_keys: ["rgb_0", "rgb_1"]
  lowdim_keys: ["eef_pos", "eef_quat", "gripper_force"]
  delta_actions: false
  port: 54281
  frame_shape:
    - 3
    - 256
    - 256