max_episode_timesteps: 600
episodes_path: "/mnt/ssd/james/episodes"

realsense:
  n_frames: ${max_episode_timesteps}
  width: 1280
  height: 720
  fps: 15

writer:
  max_episode_len: ${max_episode_timesteps}
  instruction: "Pick up the green mug and place it into the sink"
  captures:
    frame_width: ${realsense.width}
    frame_height: ${realsense.height}
    max_episode_len: ${writer.max_episode_len}
    fps: ${realsense.fps}

hydra:
  output_subdir: null
  job_logging: null
  run:
    dir: .
